"""add columns to table

Revision ID: 5051cf66d2eb
Revises: 5b733596dd83
Create Date: 2024-01-15 11:19:14.737291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5051cf66d2eb'
down_revision = '5b733596dd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
